---
# Base name of the generated objects (deployment, service, ...)
apicast_name: "{{ lookup('env','APICAST_NAME') | default('apicast', true) }}"
apicast_image: registry.access.redhat.com/3scale-amp20/apicast-gateway:1.0
apicast_replicas: 2
state: present

# Default values for optional parameters, i.e. params that are required:false
# We need to set a value for them here to prevent references to undefined params
resolver: "{{ lookup('env','APICAST_RESOLVER') | default('', true) }}"
service_list: "{{ lookup('env','APICAST_SERVICE_LIST') | default('', true) }}"
config_cache: "{{ lookup('env','APICAST_CONFIG_CACHE') | default('', true) }}"
redis_url: "{{ lookup('env','APICAST_REDIS_URL') | default('', true) }}"
config_file: "{{ lookup('env','APICAST_CONFIG_FILE') | default('', true) }}"

# Default values for other parameters
# These would have a value set from the broker through required params;
# We set defaults anyway to make it simpler to invoke the APB directly
# e.g. during testing
_apb_plan_id: default
namespace: "{{ lookup('env','NAMESPACE') | default(apicast_name, true) }}"
backend_cache_handler: strict
config_loader: boot
deploy_environment: production
log_level: notice
management_scope: status
oauth_tokens_ttl: 604800
path_routing: false
response_codes: false
tls_verify: true
